name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-node@v1
      - uses: actions/checkout@v2
      - name: Create public
        run: |
          mkdir public
          cp -rf components public
          cp -rf config public
          cp -rf fonts public
          cp -rf styles public
          cp index.html public
          cp index.js public
          cp icon.png public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public/*