name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create public
        run: |
          mkdir public
          cp -rf components public
          cp -rf config public
          cp -rf fonts public
          cp -rf styles public
          cp index.html public
          cp index.js public
          cp icon.png public
      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: public/*
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
